### ApiGateway
@baseUrl = http://localhost:5000

### GET
GET {{baseUrl}}/api/User/ViewProfile/GetPersonalData?username=foforfr
Accept: application/json

### GET
GET {{baseUrl}}/api/User/ViewProfile/GetAddresses?username=foforfr
Accept: application/json
