<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include=".env" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\base\" />
    <Folder Include="wwwroot\css\layout\" />
    <Folder Include="wwwroot\css\themes\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Google.Protobuf" Version="3.31.0" />
    <PackageReference Include="Google.Protobuf.Tools" Version="3.31.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
	<Protobuf Include="Connections\Proto\GetImageProduct.proto" GrpcServices="Client" />
	<Protobuf Include="Connections\Proto\SaveImageProduct.proto" GrpcServices="Client" />
  </ItemGroup>

</Project>
