@backend_host = https://localhost:5001

### Login POST
# Expected responses:
#   200 Ok - "Usuario encontrado."
#   400 BadRequest - "Campos vacíos."
#   401 Unauthorized - "Credenciales incorrectas."
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
POST {{backend_host}}/api/User/Auth/Login/Login
Content-Type: application/json
Accept: application/json
{
  username: "Username",
  password: "Password"
}

### ValidateEmailUser GET
# Expected responses:
#   200 Ok - "Email ligado al usuario."
#   400 BadRequest - "Campos vacíos."
#   404 NotFound - "Email no ligado al usuario."
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
GET {{backend_host}}/api/User/Auth/Login/ValidateEmailUser?username="Username"&email="Email"
Content-Type: application/json
Accept: application/json

### CreateTwoFactorCode POST
# Expected responses:
#   200 Ok - "Código doble factor creado."
#   400 BadRequest - "Campos vacíos."
#   404 NotFound - "Usuario no encontrado."
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
POST {{backend_host}}/api/User/Auth/Login/CreateTwoFactorCode
Content-Type: application/json
Accept: application/json
{
  username: "Username",
}

### ValidateTwoFactorCode GET
# Expected responses:
#   200 Ok - "Código doble factor correcto."
#   400 BadRequest - "Campos vacíos."
#   401 BadRequest - "Código doble factor incorrecto"
#   404 NotFound - "Usuario no encontrado."
#   404 NotFound - "Usuario no posee un código doble factor."
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
GET {{backend_host}}/api/User/Auth/Login/ValidateTwoFactorCode?username="Username"&twoFactorCode="TwoFactorCode"
Content-Type: application/json
Accept: application/json