@backend_host = https://localhost:5001

### Login
# Expected responses:
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
#   401 Unauthorized - "Credenciales incorrectas."
#   400 BadRequest - "Campos vacíos."
#   200 Ok - "Usuario encontrado."
POST {{backend_host}}/api/User/Auth/Login/Login
Content-Type: application/json
Accept: application/json
{
  username, password
}

### ValidateEmailUser
# Expected responses:
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
#   404 NotFound - "Email no ligado al usuario."
#   400 BadRequest - "Campos vacíos."
#   200 Ok - "Email ligado al usuario."
GET {{backend_host}}/api/User/Auth/Login/ValidateEmailUser?username="_____"&email="_____"
Content-Type: application/json
Accept: application/json

### CreateTwoFactorCode
# Expected responses:
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
#   404 NotFound - "Usuario no encontrado."
#   400 BadRequest - "Campos vacíos."
#   200 Ok - "Código doble factor creado."
POST {{backend_host}}/api/User/Auth/Login/CreateTwoFactorCode
Content-Type: application/json
Accept: application/json
{
  username, email
}

### ValidateTwoFactorCode
# Expected responses:
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
#   404 NotFound - "Usuario no posee un código doble factor."
#   404 NotFound - "Usuario no encontrado."
#   401 Unauthorized - "Código doble factor incorrecto."
#   400 BadRequest - "Campos vacíos."
#   200 Ok - "Código doble factor correcto."
GET {{backend_host}}/api/User/Auth/Login/ValidateTwoFactorCode?username="_____"&twoFactorCode="_____"
Content-Type: application/json
Accept: application/json

### DeleteTwoFactorCode
# Expected responses:
#   500 InternalServerError - $"Error interno del servidor: {ex.Message}"
#   404 NotFound - "Usuario no encontrado."
#   401 BadRequest - "Campo vacío."
#   204 NoContent - "Código doble factor eliminado."
DELETE {{backend_host}}/api/User/Auth/Login/DeleteTwoFactorCode?username="_____"
Content-Type: application/json
Accept: application/json
#####################################################################
### Logout
# Expected response:
#   204 NoContent
POST {{backend_host}}/api/User/Auth/Logout

#####################################################################
### GetPersonalData
# Expected responses:
#   500 InternalServerError
#   404 NotFound
#   400 BadRequest
#   200 Ok
GET {{backend_host}}/api/User/Profile/GetPersonalData?username="_____"
### GetAddresses
# Expected responses:
#   500 InternalServerError
#   404 NotFound
#   400 BadRequest
#   200 Ok
GET {{backend_host}}/api/User/Profile/GetAddresses?username="_____"
#####################################################################
### AddUser
# Expected responses:
#   500 InternalServerError
#   409 Conflict
#   400 BadRequest
#   200 Ok
POST {{backend_host}}/api/User/Registration/AddUser
{
  firstName, 
  middleName,
  lastName,
  username,
  email,
  areaCode,
  phoneNumber,
  password,
  roleId
}
### DeleteUser
# Expected responses:
#   500 InternalServerError
#   409 Conflict
#   400 BadRequest
#   204 NoContent
DELETE {{backend_host}}/api/User/Registration/DeleteUser
#####################################################################
### VerifyExistenceUsername
# Expected responses:
#   500 InternalServerError
#   404 NotFound
#   400 BadRequest
#   200 Ok
GET {{backend_host}}/api/User/ValidateUserData/VerifyExistenceUsername?username="_____"
### VerifyExistenceEmail
# Expected responses:
#   500 InternalServerError
#   404 NotFound
#   400 BadRequest
#   200 Ok
GET {{backend_host}}/api/User/ValidateUserData/VerifyExistenceEmail?email="_____"
### VerifyExistencePhoneNumber
# Expected responses:
#   500 InternalServerError
#   404 NotFound
#   400 BadRequest
#   200 Ok
GET {{backend_host}}/api/User/ValidateUserData/VerifyExistencePhoneNumber?username="_____"
