<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.Production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utils\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\icon-eye-close.png" />
    <Resource Include="Resources\Icons\icon-eye-open.png" />
    <Resource Include="Resources\Icons\icon-left-arrow.png" />
    <Resource Include="Resources\Icons\icon-right-arrow.png" />
    <Resource Include="Resources\Icons\icon-search.png" />
	<Resource Include="Resources\Icons\icon-user.png" />
	<Resource Include="Resources\Icons\icon-shopping-cart.png" />
	<Resource Include="Resources\Images\CarouselExample1.jpg" />
	<Resource Include="Resources\Images\CarouselExample2.jpg" />
	<Resource Include="Resources\Images\CarouselExample3.jpg" />
	<Resource Include="Resources\Images\CarouselExample4.jpg" />
	<Resource Include="Resources\Images\CarouselExample5.jpg" />
	<Resource Include="Resources\Images\CarouselExample6.jpg" />
	<Resource Include="Resources\Images\CarouselExample7.jpg" />
	<Resource Include="Resources\Images\CarouselExample8.jpg" />
	<Resource Include="Resources\Images\logo-business.jpg" />
	<Resource Include="Resources\Images\image-empty.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Connections\Proto\GetImageProduct.proto">
      <GrpcServices>Client</GrpcServices>
    </None>
    <None Update="Connections\Proto\SaveImageProduct.proto">
      <GrpcServices>Client</GrpcServices>
    </None>
  </ItemGroup>

</Project>
