### ApiGateway
@baseUrl = http://localhost:5000

### POST
POST {{baseUrl}}/api/User/Registration
Accept: application/json
{
  "firstName": "Ejemplo nombre",
  "middleName": "Ejemplo de apellido paterno",
  "lastName": "Ejemplo de apellido materno",
  "username": "Ejemplo de nombre de usuario",
  "email": "Ejemplo de correo",
  "areaCode": "Ejemplo de código de área",
  "phoneNumber": "Ejemplo de número de teléfono",
  "password": "Ejemplo de contraseña"
}

### GET
GET {{baseUrl}}api/User/ValidateUserData/VerifyExistenceUsername?username=foforfr
Accept: application/json

### GET
GET {{baseUrl}}api/User/ValidateUserData/VerifyExistenceEmail?email=foforfr007@gmail.com
Accept: application/json

### GET
GET {{baseUrl}}api/User/ValidateUserData/VerifyExistencePhoneNumber?areaCode=+52&phoneNumber=2281234567
Accept: application/json

### DELETE
DELETE {{baseUrl}}/api/User/DeleteAccount?username=foforfr