### ApiGateway
@baseUrl = http://localhost:5000

### GET
GET {{baseUrl}}/api/Auction/Auctioneer/ConsultMyAuctions/MyAuctions?username=foforfr
Accept: application/json

### GET
GET {{baseUrl}}/api/Auction/Auctioneer/ConsultMyAuctions/ViewMyAuctionDetails?id=1
Accept: application/json

### POST
POST {{baseUrl}}/api/Auction/Auctioneer/CreateAuction
Accept: application/json
{
  "name": "Ejemplo de nombre de subasta.",
  "firstPrice": 100,
  "bid": 10,
  "dateStart": "",
  "dateEnd": "",
  "description": "",
  "statusId": 1
}

### GET
GET {{baseUrl}}/api/Auction/Image?auctionId=1
Accept: application/json

### PATCH
PATCH {{baseUrl}}api/Auction/Auctioneer/UpdateAuction
{
  "id": 1,
  "statusId": 2,
}
